config:
  # Data
  train_path: ./Data/Component_Stratified_Split_Based_on_Augmentation_22_07_2025/train.csv
  valid_path: ./Data/Component_Stratified_Split_Based_on_Augmentation_22_07_2025/valid.csv
  test_path:  ./Data/Component_Stratified_Split_Based_on_Augmentation_22_07_2025/test.csv
  
  batch_size: 128     
  learning_rate: 0.0003
  num_epochs: 200
  num_workers: 20
  seed: 42
  patience: 10
  gradient_clip: 1.0
  
  # Model parameters 
  d_model: 512                        
  num_head: 8                         
  num_transformer_layers: 3           
  num_regression_head_layers: 3       
  dropout: 0.1
  num_positions: 6                  
  dim_feedforward: 1024                #(typically 2-4x d_model)
  use_property_focus: true            
  
  # Scheduler configuration (new section)
  # scheduler:
  #   type: reduce_lr_on_plateau        # Options: reduce_lr_on_plateau, cosine_annealing, one_cycle
  #   monitor: val_loss
  #   mode: min
  #   factor: 0.5                       # Factor by which to reduce learning rate
  #   patience: 10                      # Number of epochs with no improvement before reducing LR
  #   min_lr: 1.0e-6                    # Minimum learning rate
  #   cooldown: 5                       # Number of epochs to wait before resuming normal operation
  #   verbose: true                     # Whether to print a message when reducing LR
  
  model_name: AlloyTransformer_Regression_22_07_
  model_version: 3.3
  description: Transformer model for alloy property prediction with property-focused attention
