config:
  # Data
  train_path: ./Data/Standard_Training_Split/train.csv
  valid_path: ./Data/Standard_Training_Split/valid.csv
  test_path:  ./Data/All_Data_Based_06-06-2025/test_set_for_low_temp.csv
  
  batch_size: 64     
  learning_rate: 0.0003
  num_epochs: 150
  num_workers: 20
  seed: 42
  patience: 10
  gradient_clip: 1.0
  
  # Model parameters 
  d_model: 128                        
  num_head: 8                         
  num_transformer_layers: 3           
  num_regression_head_layers: 3       
  dropout: 0.0
  num_positions: 6                  
  dim_feedforward: 512                #(typically 2-4x d_model)
  use_property_focus: true            
  

  model_name: AlloyTransformer_Regression_27_07_
  model_version: 1.1
  description: Transformer model for alloy property prediction with property-focused attention
